Add refresh ability to user tokens, and expose tokens for storage
Emilgardis/twitch_oauth2 pull request #22
Opened 2020-12-11 18:05 UTC by Dinnerbone

This changes the API by adding an extra (optional) client secret field.

I also make some fields pub so that an application can retrieve them post-refresh and store them for the next run.

2020-12-11 18:22 UTC, Dinnerbone commented
I can't seem to get the output of my `cargo fmt` to match what these tests require, sorry!

2020-12-12 20:01 UTC, Emilgardis commented
wierd, could be a `rustfmt.toml` file somewhere in a subfolder

2020-12-12 20:11 UTC, Emilgardis requested changes
Looks good!

2020-12-12 20:11 UTC, Emilgardis commented on src/tokens/user_token.rs
> +    pub access_token: AccessToken,
This is already exposed with `TwitchToken::token()` which returns `&AccessToken`, however I can see the value in having this pub.

2020-12-12 20:11 UTC, Emilgardis commented on src/tokens/user_token.rs
> +        Ok(())
If no secret is available this should probably return a new error `RefreshTokenError::NoClientSecret`

2020-12-12 20:15 UTC, Emilgardis commented
looks like a fix in rustfmt https://github.com/rust-lang/rustfmt/pull/4557

2020-12-12 20:24 UTC, Emilgardis commented
thanks!

bors r+

2020-12-12 20:44 UTC, Emilgardis commented
bors r+

2020-12-12 20:50 UTC, merged